name: Build & Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            ext: tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: zip
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: tar.gz

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install musl tools (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y musl-tools

    - name: Build binary
      run: cargo build --release --target=${{ matrix.target }}

    - name: Verify Git tag matches Cargo.toml
      shell: bash
      run: |
        TAG_VERSION=${GITHUB_REF_NAME#v}
        CARGO_VERSION=$(grep '^version =' Cargo.toml | sed 's/.*"\(.*\)".*/\1/')
        if [ "$TAG_VERSION" != "$CARGO_VERSION" ]; then
          echo "Version mismatch: Git tag is $TAG_VERSION but Cargo.toml has $CARGO_VERSION"
          exit 1
        fi

    - name: Package binary
      shell: bash
      run: |
        mkdir dist
        cp target/${{ matrix.target }}/release/text-adventure-game* dist/
        cd dist
        if [[ "${{ matrix.ext }}" == "tar.gz" ]]; then
          tar -czvf ../text-adventure-game-${{ matrix.target }}.${{ matrix.ext }} *
        else
          powershell Compress-Archive -Path * -DestinationPath ../text-adventure-game-${{ matrix.target }}.${{ matrix.ext }}
        fi

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        name: text-adventure-game-${{ matrix.target }}
        tag_name: ${{ github.ref_name }}
        files: text-adventure-game-${{ matrix.target }}.${{ matrix.ext }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
